// =============================================================================
// FILE        : bank_transactions.dart
// MODULE      : Finance & Ledgers / Bank Book
// LAYER       : Database / Tables
// DESCRIPTION : Every debit/credit movement across all bank accounts.
//               Auto-entries flow in from POS (UPI/Card/NEFT payments).
//               Manual entries cover supplier payments, withdrawals, deposits.
//               Cheque lifecycle: ISSUED → PRESENTED → CLEARED / BOUNCED.
//
// CA / LEGAL NOTE:
//   • Records are NEVER hard-deleted (isVoided soft-delete pattern)
//   • Cheque number is stored for audit trail
//   • valueDate (clearing date) is separate from transactionDate
//   • reconciled flag enables bank statement matching
//
// SCHEMA      : v7
// INDEXES     : txnDate, accountId, type, chequeNumber, referenceId
// =============================================================================

import 'package:drift/drift.dart';
import 'package:lotus_erp/database/tables/base_table.dart';
import 'bank_accounts.dart';

@DataClassName('BankTransaction')
@TableIndex(name: 'idx_btxn_date', columns: {#txnDate})
@TableIndex(name: 'idx_btxn_account', columns: {#accountId})
@TableIndex(name: 'idx_btxn_type', columns: {#type})
@TableIndex(name: 'idx_btxn_cheque', columns: {#chequeNumber})
@TableIndex(name: 'idx_btxn_ref', columns: {#referenceId})
class BankTransactions extends Table with BaseTable {
  // ── Identity ───────────────────────────────────────────────────────────────
  /// Human-readable: BTXN-2025-0001
  TextColumn get txnId => text().unique()();

  /// FK → BankAccounts.id
  IntColumn get accountId =>
      integer().references(BankAccounts, #id, onDelete: KeyAction.restrict)();

  // ── Date & Time ────────────────────────────────────────────────────────────
  /// Date the transaction was initiated / recorded
  DateTimeColumn get txnDate => dateTime()();

  /// Cheque/NEFT actual clearing date (may differ from txnDate)
  DateTimeColumn get valueDate => dateTime().nullable()();

  // ── Classification ─────────────────────────────────────────────────────────
  /// CREDIT | DEBIT
  TextColumn get type => text()();

  /// See BankTransactionCategory enum values
  TextColumn get category => text()();

  // ── Financial ──────────────────────────────────────────────────────────────
  /// Always positive — direction determined by [type]
  RealColumn get amount => real().withDefault(const Constant(0.0))();

  // ── Payment Mode ───────────────────────────────────────────────────────────
  /// NEFT | RTGS | IMPS | UPI | CHEQUE | CASH_DEPOSIT | CASH_WITHDRAWAL | CARD
  TextColumn get paymentMode => text().withDefault(const Constant('NEFT'))();

  // ── Cheque Details (when paymentMode == CHEQUE) ────────────────────────────
  TextColumn get chequeNumber => text().nullable()();

  /// ISSUED | PRESENTED | CLEARED | BOUNCED
  TextColumn get chequeStatus => text().nullable()();

  DateTimeColumn get chequeDate => dateTime().nullable()();

  // ── Reference ──────────────────────────────────────────────────────────────
  TextColumn get description => text().nullable()();

  /// Source record ID: Bill.billNo, SalesOrder.id, etc.
  TextColumn get referenceId => text().nullable()();

  /// BILL | ORDER | PURCHASE | MANUAL | SALARY | EXPENSE
  TextColumn get referenceType => text().nullable()();

  /// Customer / Supplier / Party name
  TextColumn get partyName => text().nullable()();

  // ── Reconciliation ─────────────────────────────────────────────────────────
  /// true = matched with bank statement
  BoolColumn get isReconciled => boolean().withDefault(const Constant(false))();

  TextColumn get reconciliationNote => text().nullable()();

  // ── Flags ──────────────────────────────────────────────────────────────────
  /// true = auto-generated from POS/Booking (non-editable)
  BoolColumn get isAutoGenerated =>
      boolean().withDefault(const Constant(false))();

  /// Soft delete — financial records never hard-deleted
  BoolColumn get isVoided => boolean().withDefault(const Constant(false))();
  TextColumn get voidReason => text().nullable()();
}
