// =============================================================================
// FILE        : cash_transactions.dart
// MODULE      : Accounts / Cash Book
// LAYER       : Database / Tables
// DESCRIPTION : Master ledger for every cash movement in the shop.
//               Auto-generated entries come from POS bills & booking advances.
//               Manual entries cover all expense categories.
//
// SCHEMA      : v7 — customLabel column added for 'Other' category support
// INDEXES     : txnDate (primary filter), type (income/expense split),
//               referenceId (link back to bills/orders)
// =============================================================================

import 'package:drift/drift.dart';
import 'package:lotus_erp/database/tables/base_table.dart';

@DataClassName('CashTransaction')
@TableIndex(name: 'idx_cash_txn_date', columns: {#txnDate})
@TableIndex(name: 'idx_cash_txn_type', columns: {#type})
@TableIndex(name: 'idx_cash_txn_ref', columns: {#referenceId})
@TableIndex(name: 'idx_cash_txn_category', columns: {#category})
class CashTransactions extends Table with BaseTable {
  // ── Transaction Identity ──────────────────────────────────────────────────
  /// Human-readable ID: TXN-2025-0001
  TextColumn get txnId => text().unique()();

  /// Date & time of the transaction
  DateTimeColumn get txnDate => dateTime()();

  // ── Classification ────────────────────────────────────────────────────────
  /// 'INCOME' or 'EXPENSE'
  TextColumn get type => text()();

  /// Income:  SALE, ADVANCE, ORDER_DELIVERY, GIRVI_RETURN,
  ///          LOAN_RECEIVED, INTEREST_RECEIVED, MISC_INCOME, OTHER_INCOME
  /// Expense: SHOP_RENT, STAFF_SALARY, ELECTRICITY, PURCHASE_PAYMENT,
  ///          GIRVI_GIVEN, MAINTENANCE, ADVERTISING, TRANSPORT,
  ///          BANK_CHARGES, GOVT_FEES, MISC_EXPENSE, OTHER_EXPENSE
  TextColumn get category => text()();

  // ── Custom Label (for 'OTHER_*' categories) ───────────────────────────────
  /// Free-text label entered by user when category is OTHER_INCOME / OTHER_EXPENSE.
  /// e.g. "Temple Donation", "Emergency Medical", "Tool Purchase"
  TextColumn get customLabel => text().nullable()();

  // ── Financial ─────────────────────────────────────────────────────────────
  /// Always positive — direction is determined by [type]
  RealColumn get amount => real().withDefault(const Constant(0.0))();

  /// CASH | UPI | CARD | BANK | CHEQUE
  TextColumn get paymentMode => text().withDefault(const Constant('CASH'))();

  // ── Reference ─────────────────────────────────────────────────────────────
  /// Optional free-text description / note
  TextColumn get description => text().nullable()();

  /// ID of the source record (Bill.billNo, SalesOrder.id, etc.)
  TextColumn get referenceId => text().nullable()();

  /// 'BILL' | 'ORDER' | 'MANUAL'
  TextColumn get referenceType => text().nullable()();

  /// Customer / supplier / party name for quick display
  TextColumn get partyName => text().nullable()();

  // ── Flags ─────────────────────────────────────────────────────────────────
  /// true = auto-created from POS/Booking; false = manually entered
  BoolColumn get isAutoGenerated =>
      boolean().withDefault(const Constant(false))();

  /// true = soft-deleted (never hard-delete financial records)
  BoolColumn get isVoided => boolean().withDefault(const Constant(false))();

  /// Reason provided when voiding
  TextColumn get voidReason => text().nullable()();
}
