import 'dart:convert';

import 'package:crypto/crypto.dart';
import 'package:drift/drift.dart';

import 'package:lotus_erp/database/db/app_database.dart';
import '../../models/girvi/girvi_notice_action_model.dart';

class GirviNoticeActionRepository {
  GirviNoticeActionRepository(this._db);

  final AppDatabase _db;
  bool _schemaReady = false;

  Future<void> ensureSchema() async {
    if (_schemaReady) return;
    await _db.ensureGirviNoticeActionSchema();
    _schemaReady = true;
  }

  Future<int> recordNoticeDraft({
    required int girviId,
    required String noticeText,
    String performedBy = 'LOCAL_OPERATOR',
  }) {
    return recordAction(
      girviId: girviId,
      actionType: GirviNoticeActionTypes.noticeDraftCopied,
      noticeText: noticeText,
      documentHash: _documentHash(noticeText),
      performedBy: performedBy,
      actionNote: 'Legal notice draft copied for customer communication.',
    );
  }

  Future<int> recordNoticePrepared({
    required int girviId,
    required GirviNoticeType noticeType,
    required String noticeText,
    required int noticePeriodDays,
    String? autoGeneratedText,
    String performedBy = 'LOCAL_OPERATOR',
  }) async {
    final generated = _normalizeText(autoGeneratedText);
    final finalText = _normalizeText(noticeText);
    if (finalText == null) {
      throw ArgumentError.value(
          noticeText, 'noticeText', 'Notice text is required.');
    }
    final edited = generated != null && generated != finalText;
    final waitDays = noticePeriodDays <= 0 ? 7 : noticePeriodDays;
    await ensureSchema();

    return _db.transaction(() async {
      final existing = await _preparedNoticeForStage(girviId, noticeType);
      if (existing != null) {
        throw StateError('${noticeType.label} has already been saved.');
      }

      if (noticeType.stage > 1) {
        final previous = await _preparedNoticeForStage(
          girviId,
          GirviNoticeType.fromStage(noticeType.stage - 1),
        );
        if (previous == null) {
          throw StateError('Save the preceding notice before this stage.');
        }
        final availableAt = previous.noticeDeadlineAt ??
            previous.actionAt.add(Duration(days: waitDays));
        if (DateTime.now().isBefore(availableAt)) {
          throw StateError('${noticeType.label} is not yet due.');
        }
      }

      final now = DateTime.now();
      return recordAction(
        girviId: girviId,
        actionType: noticeType.actionType,
        noticeStage: noticeType.stage,
        noticeText: finalText,
        documentHash: _documentHash(finalText),
        performedBy: performedBy,
        approvedBy: performedBy,
        approvedAt: now,
        noticeDeadlineAt: now.add(Duration(days: waitDays)),
        actionAt: now,
        actionNote: [
          '${noticeType.label} approved for customer communication.',
          edited
              ? 'Final version was manually edited before approval.'
              : 'Approved version matches the generated notice.',
          if (edited) 'Original generated notice: $generated',
        ].join('\n'),
      );
    });
  }

  Future<int> recordCollateralRecoveryInitiated({
    required int girviId,
    String? note,
    int noticePeriodDays = 7,
    String performedBy = 'LOCAL_OPERATOR',
  }) async {
    await ensureSchema();
    return _db.transaction(() async {
      final finalNotice = await _preparedNoticeForStage(
        girviId,
        GirviNoticeType.finalNotice,
      );
      if (finalNotice == null) {
        throw StateError(
            'A final approved notice is required before recovery.');
      }
      final recoveryEligibleAt = finalNotice.noticeDeadlineAt ??
          finalNotice.actionAt.add(
            Duration(days: noticePeriodDays <= 0 ? 7 : noticePeriodDays),
          );
      if (DateTime.now().isBefore(recoveryEligibleAt)) {
        throw StateError('The final notice review period has not completed.');
      }
      final existing = await (_db.select(_db.girviNoticeActions)
            ..where(
              (action) =>
                  action.girviId.equals(girviId) &
                  action.actionType.equals(
                    GirviNoticeActionTypes.collateralRecoveryInitiated,
                  ),
            )
            ..limit(1))
          .getSingleOrNull();
      if (existing != null) {
        throw StateError('Collateral recovery has already been initiated.');
      }
      return recordAction(
        girviId: girviId,
        actionType: GirviNoticeActionTypes.collateralRecoveryInitiated,
        performedBy: performedBy,
        actionNote: note ??
            'Collateral moved to recovery after completion of the notice workflow.',
      );
    });
  }

  Future<int> recordDisposalSettlement({
    required int girviId,
    required double pledgedValuation,
    required double recoveredAmount,
    required double penaltyAmount,
    required double settlementTotal,
    required double customerBalanceDue,
    required double customerSurplus,
    String? note,
    String performedBy = 'LOCAL_OPERATOR',
  }) async {
    await ensureSchema();
    return _db.transaction(() async {
      final recoveryStarted = await (_db.select(_db.girviNoticeActions)
            ..where(
              (action) =>
                  action.girviId.equals(girviId) &
                  action.actionType.equals(
                    GirviNoticeActionTypes.collateralRecoveryInitiated,
                  ),
            )
            ..limit(1))
          .getSingleOrNull();
      if (recoveryStarted == null) {
        throw StateError('Collateral recovery must start before settlement.');
      }
      final alreadySettled = await (_db.select(_db.girviNoticeActions)
            ..where(
              (action) =>
                  action.girviId.equals(girviId) &
                  action.actionType
                      .equals(GirviNoticeActionTypes.disposalSettled),
            )
            ..limit(1))
          .getSingleOrNull();
      if (alreadySettled != null) {
        throw StateError('Recovery settlement is already closed.');
      }
      return recordAction(
        girviId: girviId,
        actionType: GirviNoticeActionTypes.disposalSettled,
        performedBy: performedBy,
        actionNote: note ?? 'Recovery settlement closed after final notice.',
        pledgedValuation: pledgedValuation,
        recoveredAmount: recoveredAmount,
        penaltyAmount: penaltyAmount,
        settlementTotal: settlementTotal,
        customerBalanceDue: customerBalanceDue,
        customerSurplus: customerSurplus,
      );
    });
  }

  Future<int> recordNoticeDeliveryProof({
    required int girviId,
    required GirviNoticeType noticeType,
    required String noticeText,
    required String actionType,
    required String deliveryChannel,
    required String deliveryStatus,
    String? deliveryReference,
    DateTime? deliveredAt,
    String performedBy = 'LOCAL_OPERATOR',
  }) async {
    await ensureSchema();
    return _db.transaction(() async {
      final prepared = await _preparedNoticeForStage(girviId, noticeType);
      final finalText = _normalizeText(noticeText);
      if (prepared == null || finalText == null) {
        throw StateError('Save the approved notice before recording delivery.');
      }
      if (prepared.documentHash != _documentHash(finalText)) {
        throw StateError(
            'Delivery proof must use the saved, approved notice version.');
      }
      return recordAction(
        girviId: girviId,
        actionType: actionType,
        noticeStage: noticeType.stage,
        noticeText: finalText,
        documentHash: prepared.documentHash,
        performedBy: performedBy,
        actionNote:
            '${noticeType.label} $deliveryStatus through $deliveryChannel.',
        deliveryChannel: deliveryChannel,
        deliveryStatus: deliveryStatus,
        deliveryReference: deliveryReference,
        deliveredAt: deliveredAt ?? DateTime.now(),
      );
    });
  }

  Future<int> recordAction({
    required int girviId,
    required String actionType,
    int? noticeStage,
    String? noticeText,
    String? documentHash,
    String? actionNote,
    String? performedBy,
    String? approvedBy,
    DateTime? approvedAt,
    DateTime? noticeDeadlineAt,
    DateTime? actionAt,
    double pledgedValuation = 0,
    double recoveredAmount = 0,
    double penaltyAmount = 0,
    double settlementTotal = 0,
    double customerBalanceDue = 0,
    double customerSurplus = 0,
    String? deliveryChannel,
    String? deliveryStatus,
    String? deliveryReference,
    DateTime? deliveredAt,
  }) async {
    await ensureSchema();
    final now = actionAt ?? DateTime.now();
    return _db.into(_db.girviNoticeActions).insert(
          GirviNoticeActionsCompanion.insert(
            girviId: girviId,
            actionType: actionType,
            createdAt: Value(now),
            actionAt: Value(now),
            noticeStage: Value(noticeStage),
            noticeText: Value(_normalizeText(noticeText)),
            documentHash: Value(_normalizeText(documentHash)),
            actionNote: Value(_normalizeText(actionNote)),
            performedBy: Value(_normalizeText(performedBy)),
            approvedBy: Value(_normalizeText(approvedBy)),
            approvedAt: Value(approvedAt),
            noticeDeadlineAt: Value(noticeDeadlineAt),
            pledgedValuation: Value(pledgedValuation),
            recoveredAmount: Value(recoveredAmount),
            penaltyAmount: Value(penaltyAmount),
            settlementTotal: Value(settlementTotal),
            customerBalanceDue: Value(customerBalanceDue),
            customerSurplus: Value(customerSurplus),
            deliveryChannel: Value(_normalizeText(deliveryChannel)),
            deliveryStatus: Value(_normalizeText(deliveryStatus)),
            deliveryReference: Value(_normalizeText(deliveryReference)),
            deliveredAt: Value(deliveredAt),
          ),
        );
  }

  Future<Map<int, GirviNoticeAction>> latestByGirviIds(
    List<int> girviIds,
  ) async {
    await ensureSchema();
    if (girviIds.isEmpty) return {};

    final rows = await (_db.select(_db.girviNoticeActions)
          ..where((row) => row.girviId.isIn(girviIds))
          ..orderBy([
            (row) => OrderingTerm.desc(row.actionAt),
            (row) => OrderingTerm.desc(row.id),
          ]))
        .get();

    final result = <int, GirviNoticeAction>{};
    for (final row in rows) {
      final action = _mapData(row);
      result[action.girviId] ??= action;
    }
    return result;
  }

  Future<Map<int, List<GirviNoticeAction>>> actionsByGirviIds(
    List<int> girviIds,
  ) async {
    await ensureSchema();
    if (girviIds.isEmpty) return {};

    final rows = await (_db.select(_db.girviNoticeActions)
          ..where((row) => row.girviId.isIn(girviIds))
          ..orderBy([
            (row) => OrderingTerm.desc(row.actionAt),
            (row) => OrderingTerm.desc(row.id),
          ]))
        .get();

    final result = <int, List<GirviNoticeAction>>{};
    for (final row in rows) {
      final action = _mapData(row);
      result.putIfAbsent(action.girviId, () => []).add(action);
    }
    return result;
  }

  GirviNoticeAction _mapData(GirviNoticeActionData row) {
    return GirviNoticeAction(
      id: row.id,
      girviId: row.girviId,
      actionType: row.actionType,
      noticeStage: row.noticeStage,
      noticeText: _normalizeText(row.noticeText),
      documentHash: _normalizeText(row.documentHash),
      actionNote: _normalizeText(row.actionNote),
      performedBy: _normalizeText(row.performedBy),
      approvedBy: _normalizeText(row.approvedBy),
      approvedAt: row.approvedAt,
      noticeDeadlineAt: row.noticeDeadlineAt,
      pledgedValuation: row.pledgedValuation,
      recoveredAmount: row.recoveredAmount,
      penaltyAmount: row.penaltyAmount,
      settlementTotal: row.settlementTotal,
      customerBalanceDue: row.customerBalanceDue,
      customerSurplus: row.customerSurplus,
      deliveryChannel: _normalizeText(row.deliveryChannel),
      deliveryStatus: _normalizeText(row.deliveryStatus),
      deliveryReference: _normalizeText(row.deliveryReference),
      deliveredAt: row.deliveredAt,
      actionAt: row.actionAt,
      createdAt: row.createdAt,
      updatedAt: row.updatedAt,
    );
  }

  Future<GirviNoticeActionData?> _preparedNoticeForStage(
    int girviId,
    GirviNoticeType noticeType,
  ) {
    return (_db.select(_db.girviNoticeActions)
          ..where(
            (row) =>
                row.girviId.equals(girviId) &
                row.noticeStage.equals(noticeType.stage) &
                row.actionType.equals(noticeType.actionType),
          )
          ..orderBy([(row) => OrderingTerm.desc(row.actionAt)])
          ..limit(1))
        .getSingleOrNull();
  }

  String? _normalizeText(Object? value) {
    final text = value?.toString().trim();
    if (text == null || text.isEmpty) return null;
    return text;
  }

  String _documentHash(String value) =>
      sha256.convert(utf8.encode(value.trim())).toString();
}
