// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD8vatzeawdjq3W-FhZgeycRB3UZP89A4',
    appId: '1:620763775715:web:80921f0fffa3405a843bd6',
    messagingSenderId: '620763775715',
    projectId: 'lotuserp-ca87a',
    authDomain: 'lotuserp-ca87a.firebaseapp.com',
    storageBucket: 'lotuserp-ca87a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjtph3k79l5tRaNczugx_AV5tk-qjQXQM',
    appId: '1:620763775715:android:03ad06cc14627d6c843bd6',
    messagingSenderId: '620763775715',
    projectId: 'lotuserp-ca87a',
    storageBucket: 'lotuserp-ca87a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhoOc5kHodTIEgN8xLFY5VZNng1V4f86M',
    appId: '1:620763775715:ios:b3964c370e1ef53f843bd6',
    messagingSenderId: '620763775715',
    projectId: 'lotuserp-ca87a',
    storageBucket: 'lotuserp-ca87a.firebasestorage.app',
    iosBundleId: 'com.example.lotusErp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhoOc5kHodTIEgN8xLFY5VZNng1V4f86M',
    appId: '1:620763775715:ios:b3964c370e1ef53f843bd6',
    messagingSenderId: '620763775715',
    projectId: 'lotuserp-ca87a',
    storageBucket: 'lotuserp-ca87a.firebasestorage.app',
    iosBundleId: 'com.example.lotusErp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD8vatzeawdjq3W-FhZgeycRB3UZP89A4',
    appId: '1:620763775715:web:dc6d26602b0f616f843bd6',
    messagingSenderId: '620763775715',
    projectId: 'lotuserp-ca87a',
    authDomain: 'lotuserp-ca87a.firebaseapp.com',
    storageBucket: 'lotuserp-ca87a.firebasestorage.app',
  );
}
