// =============================================================================
// FILE        : expense_model.dart
// MODULE      : Expense Entry
// LAYER       : Models
// DESCRIPTION : Immutable UI model for a single expense entry.
//               Maps directly from CashTransaction DB row (type='EXPENSE').
//               Re-uses PaymentMode & ExpenseCategory from cash_book_enums.
// =============================================================================

import 'package:intl/intl.dart';
import '../../finance/cash_book/cash_book_enums.dart';
import 'package:flutter/foundation.dart';

class ExpenseModel {
  final int id;
  final String expenseId; // Human-readable: EXP-2025-0001
  final DateTime expenseDate;
  final ExpenseCategory category;
  final String categoryLabel; // Resolved (custom for OTHER_EXPENSE)
  final double amount;
  final String amountFormatted;
  final PaymentMode paymentMode;
  final String? customLabel; // User text when category = OTHER_EXPENSE
  final String? description;
  final String? partyName;
  final String? referenceId;
  final bool isVoided;
  final bool isAutoGenerated;

  const ExpenseModel({
    required this.id,
    required this.expenseId,
    required this.expenseDate,
    required this.category,
    required this.categoryLabel,
    required this.amount,
    required this.amountFormatted,
    required this.paymentMode,
    this.customLabel,
    this.description,
    this.partyName,
    this.referenceId,
    required this.isVoided,
    required this.isAutoGenerated,
  });

  // ── Convenience Getters ───────────────────────────────────────────────────

  String get dateFormatted => DateFormat('d MMM yyyy').format(expenseDate);

  String get timeFormatted => DateFormat('hh:mm a').format(expenseDate);

  String get displayAmount => '- $amountFormatted';

  String get categoryDbValue => category.dbValue;

  bool get isOtherCategory => category == ExpenseCategory.otherExpense;

  // ── Formatter ─────────────────────────────────────────────────────────────

  static final _currencyFmt = NumberFormat.currency(
    locale: 'en_IN',
    symbol: '₹ ',
    decimalDigits: 2,
  );

  static String formatAmount(double amount) => _currencyFmt.format(amount);
}

// ── Grouped list for date-section headers ─────────────────────────────────────

class ExpenseGroup {
  final String headerLabel; // e.g. "Today", "Yesterday", "12 Apr 2025"
  final DateTime date;
  final List<ExpenseModel> entries;
  final double groupTotal;
  final String groupTotalFormatted;

  const ExpenseGroup({
    required this.headerLabel,
    required this.date,
    required this.entries,
    required this.groupTotal,
    required this.groupTotalFormatted,
  });
}
