import 'dart:typed_data';

import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../../models/girvi/girvi_notice_action_model.dart';
import '../../models/girvi/notice_auction_model.dart';

class GirviNoticePdfService {
  static const PdfColor _navy = PdfColor.fromInt(0xFF172437);
  static const PdfColor _gold = PdfColor.fromInt(0xFFC89421);
  static const PdfColor _ink = PdfColor.fromInt(0xFF111827);
  static const PdfColor _line = PdfColor.fromInt(0xFFB8C0CC);
  static const PdfColor _surface = PdfColor.fromInt(0xFFF6F8FB);
  static const PdfColor _danger = PdfColor.fromInt(0xFFB91C1C);

  Future<Uint8List> build({
    required NoticeAuctionCase item,
    required GirviNoticeType noticeType,
    required String noticeText,
  }) async {
    final document = pw.Document(
      title: '${noticeType.label} - ${item.loan.ticketNo}',
      author: 'Lotus ERP',
    );

    document.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(28),
        build: (context) => [
          _header(item, noticeType),
          pw.SizedBox(height: 14),
          _accountSummary(item),
          pw.SizedBox(height: 14),
          _noticeBody(noticeText),
          pw.SizedBox(height: 14),
          _signatureBlock(),
        ],
        footer: (context) => pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'Generated by Lotus ERP',
              style: const pw.TextStyle(color: _ink, fontSize: 8),
            ),
            pw.Text(
              'Page ${context.pageNumber} of ${context.pagesCount}',
              style: const pw.TextStyle(color: _ink, fontSize: 8),
            ),
          ],
        ),
      ),
    );

    return document.save();
  }

  pw.Widget _header(NoticeAuctionCase item, GirviNoticeType noticeType) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        color: _navy,
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                'GIRVI NOTICE',
                style: pw.TextStyle(
                  color: PdfColors.white,
                  fontSize: 20,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.SizedBox(height: 5),
              pw.Text(
                noticeType.label.toUpperCase(),
                style: pw.TextStyle(
                  color: _gold,
                  fontSize: 12,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.SizedBox(height: 8),
              pw.Text(
                'Ticket ${item.loan.ticketNo}',
                style: const pw.TextStyle(color: PdfColors.white, fontSize: 10),
              ),
            ],
          ),
          pw.Container(
            padding: const pw.EdgeInsets.symmetric(horizontal: 12, vertical: 8),
            decoration: pw.BoxDecoration(
              color: PdfColors.white,
              borderRadius: pw.BorderRadius.circular(6),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.end,
              children: [
                pw.Text(
                  DateFormat('dd MMM yyyy').format(DateTime.now()),
                  style: pw.TextStyle(
                    color: _ink,
                    fontSize: 10,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
                pw.SizedBox(height: 3),
                pw.Text(
                  noticeType.subtitle,
                  style: const pw.TextStyle(color: _ink, fontSize: 8.5),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  pw.Widget _accountSummary(NoticeAuctionCase item) {
    final account = item.account;
    return pw.Container(
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        color: _surface,
        borderRadius: pw.BorderRadius.circular(8),
        border: pw.Border.all(color: _line),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'Account Summary',
            style: pw.TextStyle(
              color: _ink,
              fontSize: 13,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
          pw.SizedBox(height: 8),
          pw.Wrap(
            spacing: 8,
            runSpacing: 8,
            children: [
              _metric('Customer', account.customerName),
              _metric('Mobile', account.customerMobile),
              _metric('Principal', _money(account.principalDue)),
              _metric('Interest', _money(account.netInterestDue)),
              _metric('Total Payable', _money(account.totalPayable), _danger),
              _metric('Pledged Value', _money(item.loan.totalValue)),
              _metric('Notices Prepared', '${item.preparedNoticeCount}/3'),
              _metric('Overdue Age', '${item.overdueDays} days'),
            ],
          ),
        ],
      ),
    );
  }

  pw.Widget _metric(String label, String value, [PdfColor color = _ink]) {
    return pw.Container(
      width: 164,
      padding: const pw.EdgeInsets.all(8),
      decoration: pw.BoxDecoration(
        color: PdfColors.white,
        borderRadius: pw.BorderRadius.circular(6),
        border: pw.Border.all(color: _line),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            label.toUpperCase(),
            style: const pw.TextStyle(color: _ink, fontSize: 7.5),
          ),
          pw.SizedBox(height: 3),
          pw.Text(
            value,
            style: pw.TextStyle(
              color: color,
              fontSize: 10.5,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
        ],
      ),
    );
  }

  pw.Widget _noticeBody(String noticeText) {
    final paragraphs = noticeText
        .split('\n')
        .map((line) => line.trimRight())
        .toList(growable: false);
    return pw.Container(
      padding: const pw.EdgeInsets.all(14),
      decoration: pw.BoxDecoration(
        color: PdfColors.white,
        borderRadius: pw.BorderRadius.circular(8),
        border: pw.Border.all(color: _line),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          for (final paragraph in paragraphs)
            paragraph.trim().isEmpty
                ? pw.SizedBox(height: 7)
                : pw.Padding(
                    padding: const pw.EdgeInsets.only(bottom: 4),
                    child: pw.Text(
                      paragraph,
                      style: const pw.TextStyle(
                        color: _ink,
                        fontSize: 10.5,
                        lineSpacing: 2.4,
                      ),
                    ),
                  ),
        ],
      ),
    );
  }

  pw.Widget _signatureBlock() {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        _signature('Customer Acknowledgement'),
        _signature('Authorised Signatory'),
      ],
    );
  }

  pw.Widget _signature(String label) {
    return pw.Container(
      width: 230,
      padding: const pw.EdgeInsets.only(top: 28),
      decoration: const pw.BoxDecoration(
        border: pw.Border(top: pw.BorderSide(color: _line, width: 1)),
      ),
      child: pw.Text(
        label,
        style: pw.TextStyle(
          color: _ink,
          fontSize: 9,
          fontWeight: pw.FontWeight.bold,
        ),
      ),
    );
  }

  String _money(double value) =>
      'Rs ${NumberFormat('#,##,##0', 'en_IN').format(value)}';
}
