// =============================================================================
// FILE        : cash_transaction_model.dart
// MODULE      : Accounts / Cash Book
// LAYER       : Models
// DESCRIPTION : Immutable UI model for a single cash ledger entry.
//               v2 — customLabel field added for 'Other' category support.
// =============================================================================

import 'package:intl/intl.dart';
import 'cash_book_enums.dart';
import 'package:flutter/foundation.dart';

class CashTransactionModel {
  final int id;
  final String txnId;
  final DateTime txnDate;
  final CashTransactionType type;
  final String categoryDbValue;

  /// Resolved display label — for OTHER_* this is the user's custom text
  final String categoryLabel;

  final double amount;
  final String amountFormatted;
  final PaymentMode paymentMode;
  final String? customLabel; // ✅ v2: raw custom text
  final String? description;
  final String? referenceId;
  final String? referenceType;
  final String? partyName;
  final bool isAutoGenerated;
  final bool isVoided;

  const CashTransactionModel({
    required this.id,
    required this.txnId,
    required this.txnDate,
    required this.type,
    required this.categoryDbValue,
    required this.categoryLabel,
    required this.amount,
    required this.amountFormatted,
    required this.paymentMode,
    this.customLabel,
    this.description,
    this.referenceId,
    this.referenceType,
    this.partyName,
    required this.isAutoGenerated,
    required this.isVoided,
  });

  // ── Convenience Getters ───────────────────────────────────────────────────

  bool get isIncome => type == CashTransactionType.income;
  bool get isExpense => type == CashTransactionType.expense;

  String get timeFormatted => DateFormat('hh:mm a').format(txnDate);

  String get dateFormatted => DateFormat('d MMM yyyy').format(txnDate);

  String get signedAmountFormatted =>
      isIncome ? '+ $amountFormatted' : '- $amountFormatted';

  // ── Formatter ─────────────────────────────────────────────────────────────

  static final _currencyFmt = NumberFormat.currency(
    locale: 'en_IN',
    symbol: 'Rs ',
    decimalDigits: 2,
  );

  static String formatAmount(double amount) => _currencyFmt.format(amount);

  // ── CopyWith ──────────────────────────────────────────────────────────────

  CashTransactionModel copyWith({
    bool? isVoided,
    String? description,
  }) {
    return CashTransactionModel(
      id: id,
      txnId: txnId,
      txnDate: txnDate,
      type: type,
      categoryDbValue: categoryDbValue,
      categoryLabel: categoryLabel,
      amount: amount,
      amountFormatted: amountFormatted,
      paymentMode: paymentMode,
      customLabel: customLabel,
      description: description ?? this.description,
      referenceId: referenceId,
      referenceType: referenceType,
      partyName: partyName,
      isAutoGenerated: isAutoGenerated,
      isVoided: isVoided ?? this.isVoided,
    );
  }
}

// ── Date Group Model ──────────────────────────────────────────────────────────

class CashTransactionGroup {
  final DateTime date;
  final String dateLabel;
  final List<CashTransactionModel> transactions;
  final double groupIncome;
  final double groupExpense;
  final double groupNet;

  const CashTransactionGroup({
    required this.date,
    required this.dateLabel,
    required this.transactions,
    required this.groupIncome,
    required this.groupExpense,
    required this.groupNet,
  });
}
