// =============================================================================
// FILE        : bank_account_model.dart
// MODULE      : Finance & Ledgers / Bank Book
// LAYER       : Models
// DESCRIPTION : Immutable UI models for Bank Account and Bank Transaction.
//               Completely decoupled from Drift-generated types — UI layer
//               never imports database internals.
// =============================================================================

import 'package:intl/intl.dart';
import 'bank_book_enums.dart';

// =============================================================================
// BANK ACCOUNT MODEL
// =============================================================================

class BankAccountModel {
  final int id;
  final String accountName;
  final String? holderName;
  final String bankName;
  final String accountNumber;
  final String accountNumberMasked; // e.g. xxxx xxxx 4532
  final String? ifscCode;
  final String? branchName;
  final BankAccountType accountType;
  final String? upiId;
  final double openingBalance;
  final String openingBalanceFormatted;
  final DateTime activeSince;
  final bool isActive;
  final bool isPrimary;
  final String? colorHex;

  // Runtime-computed (filled by repository)
  final double currentBalance;
  final String currentBalanceFormatted;
  final double totalCredit;
  final double totalDebit;

  const BankAccountModel({
    required this.id,
    required this.accountName,
    this.holderName,
    required this.bankName,
    required this.accountNumber,
    required this.accountNumberMasked,
    this.ifscCode,
    this.branchName,
    required this.accountType,
    this.upiId,
    required this.openingBalance,
    required this.openingBalanceFormatted,
    required this.activeSince,
    required this.isActive,
    required this.isPrimary,
    this.colorHex,
    required this.currentBalance,
    required this.currentBalanceFormatted,
    required this.totalCredit,
    required this.totalDebit,
  });

  /// Mask account number — show only last 4 digits
  static String maskAccountNumber(String number) {
    if (number.length <= 4) return number;
    final last4 = number.substring(number.length - 4);
    final masked = 'xxxx xxxx $last4';
    return masked;
  }

  static final _currencyFmt = NumberFormat.currency(
    locale: 'en_IN',
    symbol: '₹ ',
    decimalDigits: 2,
  );

  static String formatAmount(double v) => _currencyFmt.format(v);
}

// =============================================================================
// BANK TRANSACTION MODEL
// =============================================================================

class BankTransactionModel {
  final int id;
  final String txnId;
  final int accountId;
  final String accountName; // Denormalized for display
  final DateTime txnDate;
  final DateTime? valueDate;
  final BankTransactionType type;
  final String categoryDbValue;
  final String categoryLabel;
  final double amount;
  final String amountFormatted;
  final BankPaymentMode paymentMode;
  final String? chequeNumber;
  final ChequeStatus? chequeStatus;
  final DateTime? chequeDate;
  final String? description;
  final String? referenceId;
  final String? referenceType;
  final String? partyName;
  final bool isReconciled;
  final bool isAutoGenerated;
  final bool isVoided;

  const BankTransactionModel({
    required this.id,
    required this.txnId,
    required this.accountId,
    required this.accountName,
    required this.txnDate,
    this.valueDate,
    required this.type,
    required this.categoryDbValue,
    required this.categoryLabel,
    required this.amount,
    required this.amountFormatted,
    required this.paymentMode,
    this.chequeNumber,
    this.chequeStatus,
    this.chequeDate,
    this.description,
    this.referenceId,
    this.referenceType,
    this.partyName,
    required this.isReconciled,
    required this.isAutoGenerated,
    required this.isVoided,
  });

  // ── Convenience Getters ───────────────────────────────────────────────────
  bool get isCredit => type == BankTransactionType.credit;
  bool get isDebit => type == BankTransactionType.debit;
  bool get isCheque => paymentMode == BankPaymentMode.cheque;
  bool get isPending =>
      isCheque &&
      chequeStatus != ChequeStatus.cleared &&
      chequeStatus != ChequeStatus.bounced;

  String get timeFormatted => DateFormat('hh:mm a').format(txnDate);
  String get dateFormatted => DateFormat('d MMM yyyy').format(txnDate);

  String get signedAmountFormatted =>
      isCredit ? '+ $amountFormatted' : '- $amountFormatted';

  static final _currencyFmt = NumberFormat.currency(
    locale: 'en_IN',
    symbol: '₹ ',
    decimalDigits: 2,
  );

  static String formatAmount(double v) => _currencyFmt.format(v);
}

// =============================================================================
// TRANSACTION GROUP MODEL (for date-grouped list view)
// =============================================================================

class BankTransactionGroup {
  final DateTime date;
  final String dateLabel;
  final List<BankTransactionModel> transactions;
  final double groupCredit;
  final double groupDebit;
  final double groupNet;

  const BankTransactionGroup({
    required this.date,
    required this.dateLabel,
    required this.transactions,
    required this.groupCredit,
    required this.groupDebit,
    required this.groupNet,
  });
}
